LuaEvent = 
{
    --输入管理
    EVENT_INPUT_TOUCHSTART  = "EVENT_INPUT_TOUCHSTART",
    EVENT_INPUT_TOUCHUP     = "EVENT_INPUT_TOUCHUP",
    EVENT_INPUT_TAP         = "EVENT_INPUT_TAP",
    EVENT_INPUT_LONGTAP     = "EVENT_INPUT_LONGTAP",
    EVENT_INPUT_LONGTAPEND  = "EVENT_INPUT_LONGTAPEND",
    EVENT_INPUT_SWIPESTART  = "EVENT_INPUT_SWIPESTART",
    EVENT_INPUT_SWIPE       = "EVENT_INPUT_SWIPE",
    EVENT_INPUT_SWIPEEND    = "EVENT_INPUT_SWIPEEND",
}