//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto_server.proto
// Note: requires additional types generated from: proto_common.proto
using proto_common;
namespace proto_server
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_server_ready")]
  public partial class s2c_server_ready : global::ProtoBuf.IExtensible
  {
    public s2c_server_ready() {}
    
    private int _server_map_version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_map_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int server_map_version
    {
      get { return _server_map_version; }
      set { _server_map_version = value; }
    }
    private ulong _map_seed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"map_seed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong map_seed
    {
      get { return _map_seed; }
      set { _map_seed = value; }
    }
    private float _server_step;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"server_step", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float server_step
    {
      get { return _server_step; }
      set { _server_step = value; }
    }
    private string _world_name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"world_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string world_name
    {
      get { return _world_name; }
      set { _world_name = value; }
    }
    private string _game_name;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"game_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string game_name
    {
      get { return _game_name; }
      set { _game_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_access_denied")]
  public partial class s2c_access_denied : global::ProtoBuf.IExtensible
  {
    public s2c_access_denied() {}
    
    private uint _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _info = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_nodedef")]
  public partial class s2c_nodedef : global::ProtoBuf.IExtensible
  {
    public s2c_nodedef() {}
    
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_itemdef")]
  public partial class s2c_itemdef : global::ProtoBuf.IExtensible
  {
    public s2c_itemdef() {}
    
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_craftdef")]
  public partial class s2c_craftdef : global::ProtoBuf.IExtensible
  {
    public s2c_craftdef() {}
    
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_inventory")]
  public partial class s2c_inventory : global::ProtoBuf.IExtensible
  {
    public s2c_inventory() {}
    
    private uint _size;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint size
    {
      get { return _size; }
      set { _size = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _change_index = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"change_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> change_index
    {
      get { return _change_index; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _change_datas = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"change_datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> change_datas
    {
      get { return _change_datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_timeofday")]
  public partial class s2c_timeofday : global::ProtoBuf.IExtensible
  {
    public s2c_timeofday() {}
    
    private uint _moon;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"moon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint moon
    {
      get { return _moon; }
      set { _moon = value; }
    }
    private uint _time_of_day;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time_of_day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time_of_day
    {
      get { return _time_of_day; }
      set { _time_of_day = value; }
    }
    private uint _day_speed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"day_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint day_speed
    {
      get { return _day_speed; }
      set { _day_speed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_object_properties")]
  public partial class s2c_object_properties : global::ProtoBuf.IExtensible
  {
    public s2c_object_properties() {}
    
    private int _aid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"aid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int aid
    {
      get { return _aid; }
      set { _aid = value; }
    }
    private uint _config_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"config_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint config_id
    {
      get { return _config_id; }
      set { _config_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private bool _physical;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"physical", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool physical
    {
      get { return _physical; }
      set { _physical = value; }
    }
    private bool _need_collide_with_objects;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"need_collide_with_objects", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool need_collide_with_objects
    {
      get { return _need_collide_with_objects; }
      set { _need_collide_with_objects = value; }
    }
    private float _weight;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"weight", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float weight
    {
      get { return _weight; }
      set { _weight = value; }
    }
    private Vec3Float _collisionbox_minpos;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"collisionbox_minpos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Float collisionbox_minpos
    {
      get { return _collisionbox_minpos; }
      set { _collisionbox_minpos = value; }
    }
    private Vec3Float _collisionbox_maxpos;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"collisionbox_maxpos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Float collisionbox_maxpos
    {
      get { return _collisionbox_maxpos; }
      set { _collisionbox_maxpos = value; }
    }
    private string _mesh;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"mesh", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mesh
    {
      get { return _mesh; }
      set { _mesh = value; }
    }
    private Vec3Float _visual_size;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"visual_size", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Float visual_size
    {
      get { return _visual_size; }
      set { _visual_size = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_object_control_bits")]
  public partial class s2c_object_control_bits : global::ProtoBuf.IExtensible
  {
    public s2c_object_control_bits() {}
    
    private int _aid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"aid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int aid
    {
      get { return _aid; }
      set { _aid = value; }
    }
    private uint _flags;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint flags
    {
      get { return _flags; }
      set { _flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_object_movemont")]
  public partial class s2c_object_movemont : global::ProtoBuf.IExtensible
  {
    public s2c_object_movemont() {}
    
    private int _aid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"aid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int aid
    {
      get { return _aid; }
      set { _aid = value; }
    }
    private Vec3Float _pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Float pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private Vec3Float _speed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private Vec3Float _acceleration;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"acceleration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Float acceleration
    {
      get { return _acceleration; }
      set { _acceleration = value; }
    }
    private bool _do_interpolate;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"do_interpolate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool do_interpolate
    {
      get { return _do_interpolate; }
      set { _do_interpolate = value; }
    }
    private bool _is_movement_end;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"is_movement_end", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_movement_end
    {
      get { return _is_movement_end; }
      set { _is_movement_end = value; }
    }
    private float _update_interval;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"update_interval", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float update_interval
    {
      get { return _update_interval; }
      set { _update_interval = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_object_yaw_and_picth")]
  public partial class s2c_object_yaw_and_picth : global::ProtoBuf.IExtensible
  {
    public s2c_object_yaw_and_picth() {}
    
    private int _aid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"aid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int aid
    {
      get { return _aid; }
      set { _aid = value; }
    }
    private float _pitch;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pitch", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pitch
    {
      get { return _pitch; }
      set { _pitch = value; }
    }
    private float _yaw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"yaw", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yaw
    {
      get { return _yaw; }
      set { _yaw = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_object_init_message")]
  public partial class s2c_object_init_message : global::ProtoBuf.IExtensible
  {
    public s2c_object_init_message() {}
    
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private s2c_object_properties _properties;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"properties", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public s2c_object_properties properties
    {
      get { return _properties; }
      set { _properties = value; }
    }
    private s2c_object_movemont _movemont;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"movemont", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public s2c_object_movemont movemont
    {
      get { return _movemont; }
      set { _movemont = value; }
    }
    private s2c_object_yaw_and_picth _yawpitch;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"yawpitch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public s2c_object_yaw_and_picth yawpitch
    {
      get { return _yawpitch; }
      set { _yawpitch = value; }
    }
    private s2c_object_control_bits _control;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"control", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public s2c_object_control_bits control
    {
      get { return _control; }
      set { _control = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ao_add_param")]
  public partial class ao_add_param : global::ProtoBuf.IExtensible
  {
    public ao_add_param() {}
    
    private int _aid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"aid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int aid
    {
      get { return _aid; }
      set { _aid = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private s2c_object_init_message _ao_data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ao_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public s2c_object_init_message ao_data
    {
      get { return _ao_data; }
      set { _ao_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_ao_changed")]
  public partial class s2c_ao_changed : global::ProtoBuf.IExtensible
  {
    public s2c_ao_changed() {}
    
    private readonly global::System.Collections.Generic.List<uint> _remove_list = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"remove_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> remove_list
    {
      get { return _remove_list; }
    }
  
    private readonly global::System.Collections.Generic.List<ao_add_param> _add_list = new global::System.Collections.Generic.List<ao_add_param>();
    [global::ProtoBuf.ProtoMember(2, Name=@"add_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ao_add_param> add_list
    {
      get { return _add_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_active_object_msgs")]
  public partial class s2c_active_object_msgs : global::ProtoBuf.IExtensible
  {
    public s2c_active_object_msgs() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _ao_data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ao_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] ao_data
    {
      get { return _ao_data; }
      set { _ao_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_play_sound")]
  public partial class s2c_play_sound : global::ProtoBuf.IExtensible
  {
    public s2c_play_sound() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private float _gain;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"gain", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float gain
    {
      get { return _gain; }
      set { _gain = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private Vec3Float _pos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Float pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _object;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"object", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint @object
    {
      get { return _object; }
      set { _object = value; }
    }
    private bool _loop;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"loop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool loop
    {
      get { return _loop; }
      set { _loop = value; }
    }
    private string _category;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string category
    {
      get { return _category; }
      set { _category = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_stop_sound")]
  public partial class s2c_stop_sound : global::ProtoBuf.IExtensible
  {
    public s2c_stop_sound() {}
    
    private int _handler;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"handler", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int handler
    {
      get { return _handler; }
      set { _handler = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_remove_node")]
  public partial class s2c_remove_node : global::ProtoBuf.IExtensible
  {
    public s2c_remove_node() {}
    
    private Vec3Int32 _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Int32 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_add_node")]
  public partial class s2c_add_node : global::ProtoBuf.IExtensible
  {
    public s2c_add_node() {}
    
    private Vec3Int32 _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Int32 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private uint _param0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"param0", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint param0
    {
      get { return _param0; }
      set { _param0 = value; }
    }
    private uint _param1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }
    private uint _param2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }
    private int _removemetadata;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"removemetadata", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int removemetadata
    {
      get { return _removemetadata; }
      set { _removemetadata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_block_data_batch")]
  public partial class s2c_block_data_batch : global::ProtoBuf.IExtensible
  {
    public s2c_block_data_batch() {}
    
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_time_syn")]
  public partial class s2c_time_syn : global::ProtoBuf.IExtensible
  {
    public s2c_time_syn() {}
    
    private ulong _client_ts;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"client_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong client_ts
    {
      get { return _client_ts; }
      set { _client_ts = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_show_tips")]
  public partial class s2c_show_tips : global::ProtoBuf.IExtensible
  {
    public s2c_show_tips() {}
    
    private string _text;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_number_ext_fields_update")]
  public partial class s2c_number_ext_fields_update : global::ProtoBuf.IExtensible
  {
    public s2c_number_ext_fields_update() {}
    
    private int _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_string_ext_fields_update")]
  public partial class s2c_string_ext_fields_update : global::ProtoBuf.IExtensible
  {
    public s2c_string_ext_fields_update() {}
    
    private int _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private byte[] _val;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] val
    {
      get { return _val; }
      set { _val = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}