//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto_client.proto
// Note: requires additional types generated from: proto_common.proto
using proto_common;
namespace proto_client
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_login")]
  public partial class c2s_login : global::ProtoBuf.IExtensible
  {
    public c2s_login() {}
    
    private uint _protocol_ver;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"protocol_ver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint protocol_ver
    {
      get { return _protocol_ver; }
      set { _protocol_ver = value; }
    }
    private uint _map_ver;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"map_ver", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint map_ver
    {
      get { return _map_ver; }
      set { _map_ver = value; }
    }
    private ulong _uid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private uint _world_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"world_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint world_id
    {
      get { return _world_id; }
      set { _world_id = value; }
    }
    private ulong _login_session;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"login_session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong login_session
    {
      get { return _login_session; }
      set { _login_session = value; }
    }
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _role;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint role
    {
      get { return _role; }
      set { _role = value; }
    }
    private byte[] _token;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_logout")]
  public partial class c2s_logout : global::ProtoBuf.IExtensible
  {
    public c2s_logout() {}
    
    private uint _param;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"param", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint param
    {
      get { return _param; }
      set { _param = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_interact")]
  public partial class c2s_interact : global::ProtoBuf.IExtensible
  {
    public c2s_interact() {}
    
    private uint _action;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint action
    {
      get { return _action; }
      set { _action = value; }
    }
    private uint _item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item
    {
      get { return _item; }
      set { _item = value; }
    }
    private byte[] _pointed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pointed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] pointed
    {
      get { return _pointed; }
      set { _pointed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_inventory_action")]
  public partial class c2s_inventory_action : global::ProtoBuf.IExtensible
  {
    public c2s_inventory_action() {}
    
    private byte[] _action;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] action
    {
      get { return _action; }
      set { _action = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_damage")]
  public partial class c2s_damage : global::ProtoBuf.IExtensible
  {
    public c2s_damage() {}
    
    private int _damage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_breath")]
  public partial class c2s_breath : global::ProtoBuf.IExtensible
  {
    public c2s_breath() {}
    
    private int _breath;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"breath", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int breath
    {
      get { return _breath; }
      set { _breath = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_client_ready")]
  public partial class c2s_client_ready : global::ProtoBuf.IExtensible
  {
    public c2s_client_ready() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_player_pos")]
  public partial class c2s_player_pos : global::ProtoBuf.IExtensible
  {
    public c2s_player_pos() {}
    
    private int _posx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"posx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posx
    {
      get { return _posx; }
      set { _posx = value; }
    }
    private int _posy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"posy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posy
    {
      get { return _posy; }
      set { _posy = value; }
    }
    private int _posz;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posz", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posz
    {
      get { return _posz; }
      set { _posz = value; }
    }
    private int _speedx;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"speedx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int speedx
    {
      get { return _speedx; }
      set { _speedx = value; }
    }
    private int _speedy;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"speedy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int speedy
    {
      get { return _speedy; }
      set { _speedy = value; }
    }
    private int _speedz;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"speedz", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int speedz
    {
      get { return _speedz; }
      set { _speedz = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_player_pitch_yaw")]
  public partial class c2s_player_pitch_yaw : global::ProtoBuf.IExtensible
  {
    public c2s_player_pitch_yaw() {}
    
    private int _pitch;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pitch", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pitch
    {
      get { return _pitch; }
      set { _pitch = value; }
    }
    private int _yaw;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"yaw", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int yaw
    {
      get { return _yaw; }
      set { _yaw = value; }
    }
    private Vec3Float _camera_dir;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"camera_dir", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Float camera_dir
    {
      get { return _camera_dir; }
      set { _camera_dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_player_item")]
  public partial class c2s_player_item : global::ProtoBuf.IExtensible
  {
    public c2s_player_item() {}
    
    private uint _item;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_respawn")]
  public partial class c2s_respawn : global::ProtoBuf.IExtensible
  {
    public c2s_respawn() {}
    
    private Vec3Int32 _respawn_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"respawn_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Int32 respawn_pos
    {
      get { return _respawn_pos; }
      set { _respawn_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_removenode")]
  public partial class c2s_removenode : global::ProtoBuf.IExtensible
  {
    public c2s_removenode() {}
    
    private Vec3Int32 _removenode_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"removenode_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Int32 removenode_pos
    {
      get { return _removenode_pos; }
      set { _removenode_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_block_data")]
  public partial class c2s_block_data : global::ProtoBuf.IExtensible
  {
    public c2s_block_data() {}
    
    private Vec3Int32 _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Int32 pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private byte[] _hash;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] hash
    {
      get { return _hash; }
      set { _hash = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_block_data_batch")]
  public partial class c2s_block_data_batch : global::ProtoBuf.IExtensible
  {
    public c2s_block_data_batch() {}
    
    private uint _distance;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint distance
    {
      get { return _distance; }
      set { _distance = value; }
    }
    private readonly global::System.Collections.Generic.List<c2s_block_data> _blocks = new global::System.Collections.Generic.List<c2s_block_data>();
    [global::ProtoBuf.ProtoMember(2, Name=@"blocks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<c2s_block_data> blocks
    {
      get { return _blocks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_time_syn")]
  public partial class c2s_time_syn : global::ProtoBuf.IExtensible
  {
    public c2s_time_syn() {}
    
    private ulong _client_ts;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"client_ts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong client_ts
    {
      get { return _client_ts; }
      set { _client_ts = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_analyse_behavior")]
  public partial class c2s_analyse_behavior : global::ProtoBuf.IExtensible
  {
    public c2s_analyse_behavior() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _detail;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"detail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string detail
    {
      get { return _detail; }
      set { _detail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_updatemeta_node_style")]
  public partial class c2s_updatemeta_node_style : global::ProtoBuf.IExtensible
  {
    public c2s_updatemeta_node_style() {}
    
    private Vec3Int32 _meta_pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"meta_pos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Vec3Int32 meta_pos
    {
      get { return _meta_pos; }
      set { _meta_pos = value; }
    }
    private string _node_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"node_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string node_name
    {
      get { return _node_name; }
      set { _node_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_player_keypress")]
  public partial class c2s_player_keypress : global::ProtoBuf.IExtensible
  {
    public c2s_player_keypress() {}
    
    private uint _keypressed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"keypressed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint keypressed
    {
      get { return _keypressed; }
      set { _keypressed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_update_client_config")]
  public partial class c2s_update_client_config : global::ProtoBuf.IExtensible
  {
    public c2s_update_client_config() {}
    
    private uint _max_block_send_distance = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"max_block_send_distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_block_send_distance
    {
      get { return _max_block_send_distance; }
      set { _max_block_send_distance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}