//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class INodeDefManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal INodeDefManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(INodeDefManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~INodeDefManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mcworld_client_corePINVOKE.delete_INodeDefManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual IContentFeatures getDef(ushort c) {
    IContentFeatures ret = new IContentFeatures(mcworld_client_corePINVOKE.INodeDefManager_getDef__SWIG_0(swigCPtr, c), false);
    return ret;
  }

  public virtual IContentFeatures getDef(IMapNode n) {
    IContentFeatures ret = new IContentFeatures(mcworld_client_corePINVOKE.INodeDefManager_getDef__SWIG_1(swigCPtr, IMapNode.getCPtr(n)), false);
    if (mcworld_client_corePINVOKE.SWIGPendingException.Pending) throw mcworld_client_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual IContentFeatures getDef(string name) {
    IContentFeatures ret = new IContentFeatures(mcworld_client_corePINVOKE.INodeDefManager_getDef__SWIG_2(swigCPtr, name), false);
    if (mcworld_client_corePINVOKE.SWIGPendingException.Pending) throw mcworld_client_corePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
